name: cv_term_project
channels:
  - defaults
dependencies:
  - astroid=2.5
  - autopep8=1.5.6
  - blas=1.0
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - colorama=0.4.4
  - freetype=2.10.4
  - hdf5=1.8.20
  - icc_rt=2019.0.0
  - intel-openmp=2021.2.0
  - isort=5.8.0
  - jpeg=9b
  - lazy-object-proxy=1.6.0
  - libopencv=3.4.2
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.9.3
  - mccabe=0.6.1
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - numpy=1.20.1
  - numpy-base=1.20.1
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1k
  - pillow=8.2.0
  - pip=21.0.1
  - py-opencv=3.4.2
  - pycodestyle=2.7.0
  - pylint=2.7.4
  - python=3.7.10
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - toml=0.10.2
  - typed-ast=1.4.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - wrapt=1.12.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.12.0
    - attrs==21.2.0
    - mediapipe==0.8.4.2
    - opencv-contrib-python==4.5.2.52
    - scipy==1.6.3
    - xgboost==1.4.2